included: # paths to include during linting. `--path` is ignored if present.
    - Spot

disabled_rules: # rule identifiers turned on by default to exclude from running
    - function_body_length
    - identifier_name
    - missing_docs
    - sorted_imports
    - trailing_whitespace
    - function_parameter_count

opt_in_rules: # some rules are turned off by default, so you need to opt-in
    - empty_count
    - closure_end_indentation
    - closure_spacing
    - comments_space
    - comments_capitalized_ignore_possible_code
    - comments_capitalized_find_possible_code
    - explicit_init
    - explicit_failure_calls
    - extension_access_modifier
    - fatal_error_message
    - first_where
    - force_cast
    - force_unwrapping
    - implicitly_unwrapped_optional
    - multiline_parameters
    - multiple_empty_lines
    - nesting
    - number_separator
    - operator_usage_whitespace
    - overridden_super_call
    - private_outlet
    - prohibited_super_call
    - protocol_property_accessors_order
    - redundant_nil_coalescing
    - syntactic_sugar
    - vertical_parameter_alignment_on_call
    - vertical_whitespace

excluded: # paths to ignore during linting. Takes precedence over `included`.
    - Carthage
    - Pods

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast:
    severity: warning

force_try:
    severity: warning

shorthand_operator:
    severity: warning

variable_name:
    severity: warning

cyclomatic_complexity:
    - 20

line_length:
    - 200

empty_count:
    severity: warning

type_body_length:
    - 300

file_length:
    - 500

type_name:
    excluded: iPhone # excluded via string
    allowed_symbols: ["_"] # these are allowed in type names
    severity: warning

large_tuple:
    warning: 4
    error: 5

colon:
    severity: warning

comma: warning
legacy_constant: warning
legacy_constructor: warning
opening_brace: warning
trailing_newline: warning
trailing_semicolon: warning

custom_rules:
    comments_space: # From https://github.com/brandenr/swiftlintconfig
    name: "Space After Comment"
    regex: '(^ *//\w+)'
    message: "There should be a space after //"
    severity: warning
    explicit_failure_calls:
        name: “Avoid asserting ‘false’”
        regex: ‘((assert|precondition)\(false)’
        message: “Use assertionFailure() or preconditionFailure() instead.”
        severity: warning
    
    multiple_empty_lines:
        name: "Multiple Empty Lines"
        regex: '((?:\s*\n){3,})'
        message: "There are too many line breaks"
        severity: warning
        
# Disabling because this causes unnecessary errors. Renable when it's time to fix these rules.
#identifier_name:
#  excluded: # excluded via string array
#    - id
#    - URL
#    - GlobalAPIKey
