included: # paths to include during linting. `--path` is ignored if present.
    - Spot

disabled_rules: # rule identifiers turned on by default to exclude from running
    - function_body_length

opt_in_rules: # some rules are turned off by default, so you need to opt-in
    - empty_count

excluded: # paths to ignore during linting. Takes precedence over `included`.
    - Carthage
    - Pods

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast:
    severity: warning

force_try:
    severity: warning
    
shorthand_operator:
    severity: warning
    
identifier_name:
    severity: warning
    allowed_symbols: "_"
    min_length:
        warning: 1
    severity: warning

cyclomatic_complexity:
    - 20

line_length:
    - 200
    
empty_count:
    severity: warning

type_body_length:
    - 300

file_length:
    - 500

type_name:
    excluded: iPhone # excluded via string
    allowed_symbols: ["_"] # these are allowed in type names
    min_length:
        warning: 1
    severity: warning
